### ISSUE TITLE
Personal Information

### ISSUE THREAD

**Issue by Richard-Dietrich** [rlmead/gather-here#25]
Registration Requirements
Section 1.  Personal Information
First Name
Surname
Email
DOB ( date of birth)
Post code/zipcode
Distance prepared to travel to meet people, in mile from their post code
2-factor authentication
T & C box to tick.
Create password and confirm password

**Comment by rlmead** [comment]
Part of #7; specifications are outlined on the Registration & Profile section of [the Site Specifications wiki page](https://sites.google.com/view/gather-here/project-details/how-it-works/site-specifications?authuser=0).
