### ISSUE TITLE
Video Chat Preferences

### ISSUE THREAD

**Issue by Richard-Dietrich** [rlmead/gather-here#26]
Section 2 Video chat preference
(This section is where people tell us about their video chat preferences)

The text should read:   Tick the application(s) you can use

Then they should be offered as a tick box menu with:

	Skype
	Google duo
	Zoom.
	FaceTime
	Team

**Comment by rlmead** [comment]
Part of #7; these specifications are outlined on the Registration & Profile section of [the Site Specifications wiki page](https://sites.google.com/view/gather-here/project-details/how-it-works/site-specifications?authuser=0).
