### ISSUE TITLE
Interests List

### ISSUE THREAD

**Issue by Richard-Dietrich** [rlmead/gather-here#27]
Section 3
The next part of the registration process is a tick box menu covering people interests.
The spread sheet of Interests should be made visible on the website so that visitors can see it.
It should be able to grow and change as we proceed. But at first, at the point of registration people only need to see the list of Categories

The text should read:   
Tick the items that interest you.
These fields are required.
Cultural Fun
Games
Current Affairs
Social Policy 
Science
Medicine
Economics
Environment.
Geopolitics
Societal
Technology
Living in the Third Age

The site will  perform an automatic matching process and assign a Group Number ( ID) to all members of the group and a different person ID number to each register member.

**Comment by rlmead** [comment]
Part of #7; these specifications are outlined on the Registration & Profile section of [the Site Specifications wiki page](https://sites.google.com/view/gather-here/project-details/how-it-works/site-specifications?authuser=0).
