### ISSUE TITLE
Group Matching Algorithm

### ISSUE THREAD

**Issue by Richard-Dietrich** [rlmead/gather-here#28]
The Matching Process for Automatic Group formation
The matching process should select people according to Postcode ( Location), distance they were prepared to travel from their postcode ,and critically their  interest categories and topics.

Interests have 12 categories and each category has many topics.
The matching algorithm should provide the administrator with the option to adjust the number of Interest categories and topics required to make a group match.

Initially the matching criteria should be set to one interest category only.
Provide a way for the administrator to switch all individual matching fields on and off in response to the site traffic.  Eg at first the Video Chat preference should be turned ON
In the case of the number of group members this should enable switching from 2 through to 7.
Note in same cases, eg in remote areas, it may be impossible to find 7 people.

Note
The reason for this is that until membership registration reaches a critical mass, the matching will be difficult. But as the site reaches a critical mass then we can increase the matching criteria which will improve the chance of group success.

**Comment by rlmead** [comment]
Duplicate with #10
